In [59]:
"""IMPORTING MODULES AND DATASET"""
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
import networkx as nx
import scipy
import numpy as np


In [61]:
def read_integers(path):
    content_lst=[]
    with open(path,'r') as file:
        content=file.read()
        for i in content.split('\n'):
            content_lst+=i.split(', ')
        return content_lst

names = read_integers('patient.txt')
names.pop()
print(names)
patient_number = len(names)
print(patient_number)

['104416', '105620', '105923', '106016', '107725', '108222', '110007', '111716', '113922', '114217', '114621', '115017', '116726', '120717', '122317', '122822', '129129', '140824', '154835', '158136', '159138', '162026', '163331', '166438', '167238', '168341', '170631', '173132', '173536', '173738', '175540', '175742', '176239', '178647', '180432', '180735', '182032', '182436', '183034', '183337', '187547', '198350', '200109', '200311', '209127', '211720', '214625', '250932', '285345', '285446', '310621', '321323', '333330', '467351', '555651', '588565']
56


In [62]:
"""THIS PART IS FOR LOADING SEMA'S DATASET"""
ts = np.loadtxt('HCP dataset-56 fMRI/TS_HCP/subj_104416_ts', delimiter = ',')
sig = []
for i in range(patient_number):
    sig.append(np.loadtxt('HCP dataset-56 fMRI/TS_HCP/subj_' + str(names[i]) +'_ts', delimiter = ','))

In [63]:
"""THIS PART IS FOR LOADING YOUR OWN DATASET"""
G = []
for i in range(patient_number):
    G.append(np.loadtxt(open('/home/duc/connectorhub/Connectome (new)-20240131T201631Z-001/Connectome (new)/subj_' + str(names[i]) + '_mmp1.csv','rb'), delimiter=",")[0:360,0:360])
print(G)

[array([[0.        , 0.        , 0.23862321, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00344828, ..., 0.        , 0.        ,
        0.        ],
       [0.23862321, 0.00344828, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.29439809],
       [0.        , 0.        , 0.        , ..., 0.        , 0.29439809,
        0.        ]]), array([[0.        , 0.        , 0.22945612, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.22945612, 0.        , 0.        , ..., 0.        , 0.00121655,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0

In [2]:
import scipy
info = scipy.io.loadmat("eeg_signal.mat")
sig = info["f"]
G = info["A"]

In [64]:
G_nx = []
for i in range(patient_number):
    G_nx.append(nx.from_numpy_array(G[i])) #creating graph from the patients
print(len(G_nx))
print(G_nx)

56
[<networkx.classes.graph.Graph object at 0x7fa231f5d540>, <networkx.classes.graph.Graph object at 0x7fa1f2d942e0>, <networkx.classes.graph.Graph object at 0x7fa231f76b90>, <networkx.classes.graph.Graph object at 0x7fa2403b1a20>, <networkx.classes.graph.Graph object at 0x7fa2403b1cc0>, <networkx.classes.graph.Graph object at 0x7fa21ff67d00>, <networkx.classes.graph.Graph object at 0x7fa24011fdf0>, <networkx.classes.graph.Graph object at 0x7fa2402c55a0>, <networkx.classes.graph.Graph object at 0x7fa2305891e0>, <networkx.classes.graph.Graph object at 0x7fa230589ae0>, <networkx.classes.graph.Graph object at 0x7fa230589c60>, <networkx.classes.graph.Graph object at 0x7fa2305888e0>, <networkx.classes.graph.Graph object at 0x7fa230588220>, <networkx.classes.graph.Graph object at 0x7fa24016f9d0>, <networkx.classes.graph.Graph object at 0x7fa230588f10>, <networkx.classes.graph.Graph object at 0x7fa2305884f0>, <networkx.classes.graph.Graph object at 0x7fa230589c00>, <networkx.classes.graph.Gra

In [5]:
scipy.io.savemat(file_name = "adjacency.mat", mdict = {'A_nx': G})

In [69]:
#calculating the community partition of every patient
import numpy as np 
comm = []
for k in range(patient_number):
    comm_object = nx.community.louvain_communities(G_nx[k], seed = 1)
    for i in range(len(comm_object)):
        comm_object[i] = np.array(list(comm_object[i]))
    print(np.array(comm_object, dtype = 'object'))
    comm.append(np.array(comm_object, dtype = 'object'))
comm = np.asarray(comm, dtype = 'object')
print(comm)
scipy.io.savemat(file_name = "comm.mat", mdict = {'comm0': comm})


[array([  0,   1,   2,   3,   4,   5,   6, 134, 137,  12, 141, 140,  15,
         16, 145, 144,  18, 142,  17,  19, 151, 152, 153, 154,  20,  21,
         22, 155, 159, 156, 157, 162, 158, 171,  45,  48,  49, 117, 118,
        119, 120, 121, 125, 126])
 array([ 68,  13,  14,  26,  28,  29,  30,  31, 160,  33,  34,  32, 161,
         37,  36,  38,  40,  41,  44, 178, 179,  56,  57,  58,  59,  61,
         62])
 array([ 10,  25, 163, 164, 165, 168, 169, 170,  42,  60,  63,  64,  65,
         66,  67,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  97, 107, 108, 109, 110, 111])
 array([128, 129, 130, 131, 132, 133,   7,   8,   9, 135,  11, 136, 138,
        139, 143, 146, 147, 148, 149, 150,  23,  24,  27,  35, 166, 167,
         39,  43, 172, 173,  46,  47, 174, 175,  50,  51,  52,  53,  54,
         55, 176, 177,  94,  95,  96,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 112, 113, 114,

In [66]:
comm_matrix = []
for k in range(patient_number):
    subgraph_matrix = []
    for i in range(len(comm[k])):
        subgraph_matrix.append(nx.adjacency_matrix(G_nx[k].subgraph(comm[k][i])))
    comm_matrix.append(subgraph_matrix)
comm_matrix_object = np.asarray(comm_matrix, dtype="object")           #This fixes the bug where you can't save the matrix because it isn't a homogenous list
print(comm_matrix_object)
scipy.io.savemat(file_name = "comm_matrix.mat", mdict = {'matrices': comm_matrix_object})

[list([<44x44 sparse array of type '<class 'numpy.float64'>'
 	with 1058 stored elements in Compressed Sparse Row format>, <27x27 sparse array of type '<class 'numpy.float64'>'
 	with 496 stored elements in Compressed Sparse Row format>, <46x46 sparse array of type '<class 'numpy.float64'>'
 	with 1062 stored elements in Compressed Sparse Row format>, <63x63 sparse array of type '<class 'numpy.float64'>'
 	with 2154 stored elements in Compressed Sparse Row format>, <42x42 sparse array of type '<class 'numpy.float64'>'
 	with 950 stored elements in Compressed Sparse Row format>, <21x21 sparse array of type '<class 'numpy.float64'>'
 	with 358 stored elements in Compressed Sparse Row format>, <66x66 sparse array of type '<class 'numpy.float64'>'
 	with 1722 stored elements in Compressed Sparse Row format>, <51x51 sparse array of type '<class 'numpy.float64'>'
 	with 1536 stored elements in Compressed Sparse Row format>])
 list([<41x41 sparse array of type '<class 'numpy.float64'>'
 	with

In [68]:
print(G[1].shape)
print(sig[1].shape)
scipy.io.savemat(file_name = "structural.mat", mdict = {'A0': G})
scipy.io.savemat(file_name = "timeseries.mat", mdict = {'f0': sig})

(360, 360)
(1190, 360)


In [ ]:
print(sig.shape)
sig_matrix = []
for k in range(20):
    sig_subgraph_matrix = []
    for i in range(len(comm[k])):
        sig_subgraph_matrix.append(scipy.sparse.csr_matrix(sig[k][comm[k][i]]))
    sig_matrix.append(sig_subgraph_matrix)
sig_object = np.asarray(sig_matrix, dtype="object") 
scipy.io.savemat(file_name = "sig_matrix.mat", mdict = {'signal': sig_object})

(20, 64, 50)
